#!/usr/bin/env python3
"""Render Foundations III mechanization disclosure includes.

The Lean validator owns build/declaration/axiom checking.  This script owns the
paper-facing disclosure surface: the Appendix F claim-to-Lean table.  It intentionally accepts extra manifest keys that the
validator ignores.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:  # Python 3.11+
    import tomllib  # type: ignore
except ModuleNotFoundError:  # Python 3.10 in the current environment
    import tomli as tomllib  # type: ignore


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "lean" / "manifest.toml"
INVENTORY = ROOT / "lean" / "paper_inventory.toml"
TABLE = ROOT / "paper" / "includes" / "mechanization_disclosure_table.tex"
SECTIONS = ROOT / "paper" / "sections"


SPECIALS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}

ALLOWED_COVERAGE = {
    "direct proof",
    "direct proof under stated hypotheses",
    "partial proof",
    "record projection",
    "schema mirror",
}



def tex_escape(text: object) -> str:
    return "".join(SPECIALS.get(ch, ch) for ch in str(text))


def tex_path(text: object) -> str:
    raw = str(text).replace("}", r"\}").replace("{", r"\{")
    return r"\path{" + raw + "}"






def claim_strength(entry: dict[str, object]) -> str:
    if "paper_claim_strength" in entry:
        return str(entry["paper_claim_strength"])
    kind = str(entry.get("kind", ""))
    if kind == "model_theorem":
        return "model-grade"
    if kind == "proposition":
        return "audit-grade" if "mechanization-target" in str(entry.get("paper_label", "")) else "proposition-grade"
    return "theorem-grade"


def coverage_class(entry: dict[str, object]) -> str:
    value = str(entry["coverage_class"])
    if value not in ALLOWED_COVERAGE:
        raise ValueError(f"invalid coverage class for {entry['paper_label']}: {value}")
    return value


def scope_note(entry: dict[str, object]) -> str:
    return str(entry["lean_scope"])


def body_location(entry: dict[str, object]) -> str:
    if "body_location" in entry:
        return str(entry["body_location"])
    section = str(entry.get("paper_section", "?"))
    if section == "15":
        return "Appendix F"
    return f"Section {section}"


def paper_name(entry: dict[str, object]) -> str:
    return str(entry.get("paper_name") or entry.get("description") or entry.get("paper_label"))




def load_manifest() -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    with MANIFEST.open("rb") as f:
        data = tomllib.load(f)
    with INVENTORY.open("rb") as f:
        inventory = tomllib.load(f)
    definitions, claims = data.get("definition", []), data.get("claim", [])
    entries = definitions + claims
    labels = [str(entry["paper_label"]) for entry in entries]
    expected = {
        str(entry["paper_label"])
        for kind in ("definition", "claim")
        for entry in inventory.get(kind, [])
        if entry.get("required", True)
    }
    if len(labels) != len(set(labels)) or set(labels) != expected:
        raise ValueError("manifest must contain each required paper label exactly once")
    for entry in entries:
        coverage_class(entry)
        if "footnote_wording_class" in entry or "lean_status" in entry or not entry.get("lean_scope"):
            raise ValueError(f"obsolete or missing Lean scope for {entry['paper_label']}")
    return definitions, claims




def render_table(definitions: list[dict[str, object]], claims: list[dict[str, object]]) -> str:
    rows: list[str] = []
    for entry in definitions + claims:
        lean_decl = str(entry.get("lean_decl", ""))
        supporting = entry.get("supporting_decls", [])
        lean_decls = [lean_decl] + [
            str(item if isinstance(item, str) else item["decl"])
            for item in supporting
        ]
        label = str(entry.get("paper_label", ""))
        rows.append(
            " & ".join(
                [
                    tex_path(label),
                    tex_escape(paper_name(entry)),
                    tex_escape(body_location(entry)),
                    r"\newline ".join(tex_path(decl) for decl in lean_decls),
                    tex_escape(claim_strength(entry) if label.startswith(("thm:", "model:", "prop:")) else "definition"),
                    tex_escape(coverage_class(entry)),
                    tex_escape(scope_note(entry)),
                ]
            )
            + r"\tabularnewline"
        )

    return "\n".join(
        [
            "% Generated by scripts/render_mech_disclosure.py; do not edit by hand.",
            r"\begin{landscape}",
            r"\begingroup\scriptsize",
            r"\setlength{\tabcolsep}{2pt}",
            r"\setlength{\LTleft}{0pt}",
            r"\setlength{\LTright}{0pt}",
            r"\begin{longtable}{@{}>{\raggedright\arraybackslash}p{0.12\linewidth}>{\raggedright\arraybackslash}p{0.17\linewidth}>{\raggedright\arraybackslash}p{0.08\linewidth}>{\raggedright\arraybackslash}p{0.18\linewidth}>{\raggedright\arraybackslash}p{0.09\linewidth}>{\raggedright\arraybackslash}p{0.16\linewidth}>{\raggedright\arraybackslash}p{0.09\linewidth}@{}}",
            r"\toprule",
            r"Paper label & Paper name & Body location & Lean declarations & Claim strength & Coverage class & Lean scope\tabularnewline",
            r"\midrule",
            r"\endhead",
            *rows,
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            r"\end{landscape}",
            "",
        ]
    )


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        old = path.read_text() if path.exists() else None
        if old != content:
            print(f"stale or missing generated file: {path.relative_to(ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def check_no_footnote_uses() -> bool:
    """Lean coverage is disclosed in the Appendix F table only; the body carries no Lean footnotes."""
    body = "\n".join(path.read_text() for path in sorted(SECTIONS.glob("*.md")))
    uses = sorted(set(re.findall(r"\\MechFoot[A-Za-z]+", body)))
    for macro in uses:
        print(f"unexpected Lean footnote macro {macro} in paper/sections", file=sys.stderr)
    return not uses


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    definitions, claims = load_manifest()
    ok = True
    ok &= write_or_check(TABLE, render_table(definitions, claims), args.check)
    if args.check:
        ok &= check_no_footnote_uses()
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
